DROP TABLE IF EXISTS CURRENCY_TYPE;

-- 幣別對應表
CREATE TABLE CURRENCY_TYPE (
	CURRENCY_ID INTEGER PRIMARY KEY auto_increment, -- ID
   	CURRENCY_CODE VARCHAR(10) NOT NULL, -- 幣別(英文)
	CURRENCY_NAME NVARCHAR(5) NOT NULL -- 幣別(中文)
);

INSERT INTO CURRENCY_TYPE(CURRENCY_CODE, CURRENCY_NAME) VALUES ('USD', '美元');
INSERT INTO CURRENCY_TYPE(CURRENCY_CODE, CURRENCY_NAME) VALUES ('GBP', '英鎊');
INSERT INTO CURRENCY_TYPE(CURRENCY_CODE, CURRENCY_NAME) VALUES ('EUR', '歐元');

SELECT * FROM CURRENCY_TYPE;